In [1]:
#Create a DataFrame with Pandas
import pandas as pd

d = {'col1': [1, 2, 3, 4, 7], 'col2': [4, 5, 6, 9, 5], 'col3': [7, 8, 12, 1, 11]}
df = pd.DataFrame(data=d)
print(df)


   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11


In [2]:
#Count the number of columns:

count_column = df.shape[1]
print(count_column)

3


In [3]:
#We can use df.shape[0] to find the number of rows:

#Count the number of rows:

count_row = df.shape[0]
print(count_row)

5


In [4]:
#The max() function
#The Python max() function is used to find the highest value in an array.


Average_pulse_max = max(80, 85, 90, 95, 100, 105, 110, 115, 120, 125)
print (Average_pulse_max)

125


In [5]:
#The min() function
#The Python min() function is used to find the lowest value in an array.


Average_pulse_min = min(80, 85, 90, 95, 100, 105, 110, 115, 120, 125)
print (Average_pulse_min)


80


In [6]:
#The mean() function
#The NumPy mean() function is used to find the average value of an array.

import numpy as np

Calorie_burnage = [240, 250, 260, 270, 280, 290, 300, 310, 320, 330]
Average_calorie_burnage = np.mean(Calorie_burnage)
print(Average_calorie_burnage)

285.0


In [8]:
#Extract and Read Data With Pandas
import pandas as pd

health_data = pd.read_csv("data.csv", header=0, sep=",")
print(health_data)


FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [ ]:
#Data Types

print(health_data.info())

In [ ]:
#Plot the Existing Data in Python

import matplotlib.pyplot as plt

health_data.plot(x ='Average_Pulse', y='Calorie_Burnage', kind='line'),
plt.ylim(ymin=0)
plt.xlim(xmin=0)

plt.show()

In [ ]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

In [13]:
#Numpy

In [ ]:
import numpy as np

In [ ]:
a=np.array([12, 333, 54, 3, 2, 1])

In [ ]:
type(a)

In [ ]:
a.dtype

In [ ]:
b=np.array([12, 333, 54, 6, 4, 1])

b.size

In [ ]:
b.shape

In [ ]:
b.size

In [ ]:
b.ndim

In [ ]:
c=np.array([4.3,55.8,99.23,45.9])

In [ ]:
c

In [ ]:
cities=np.array([4.3,55.8,99.23,45.9])

In [ ]:
c

In [ ]:
cities

In [ ]:
e=np.array([True, True, False, True])

In [9]:
e

NameError: name 'e' is not defined

In [ ]:
a[1]

In [ ]:
c[-1]

In [ ]:
e[2]

In [ ]:
a=np.array([[2,7,3,1,9],[55,33,22,11,66]])

In [ ]:
a

In [ ]:
a[0]

In [ ]:
a[0][3]

In [ ]:
a[0,3]

In [ ]:
b=np.array([2,3,6,8,9,7])

In [ ]:
b

In [ ]:
b[2:5]

In [ ]:
a

In [ ]:
#a[row_start:row_end,col_start:col_end]

In [ ]:
a[0:2,1:3]

In [ ]:
b[2]

In [ ]:
a

In [ ]:
a[1,0]=888

In [ ]:
a

In [ ]:
b=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

In [ ]:
b

In [ ]:
type(b)

In [ ]:
b[0][0][0]

In [ ]:
b[0,0,0]

In [ ]:
b[1,0,1]

In [ ]:
#array initializationwith diff method

In [ ]:
x=np.zeros((4,4))

In [ ]:
x

In [ ]:
x=np.zeros((4,4),dtype='int8')

In [ ]:
x

In [ ]:
x=np.ones((4,3))

In [ ]:
x

In [ ]:
x=np.full((4,4),11)

In [ ]:
x

In [ ]:
y=np.full_like((x,101)
               

In [ ]:
y

In [ ]:
#ctreate array with random var

In [ ]:
np.random.randint(1,100)

In [ ]:
a=np.random

In [ ]:
a=np.arange(22,66,2)
a

In [10]:
a=np.array([1,2,3,4])
a1=np.repeat(a,3)
a1

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [11]:
a=np.array([[1,2,3,4]])
a1=np.repeat(a,3,axis=0)
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [12]:
a=np.array([[1,2,3,4]])
a1=np.repeat(a,3,axis=1)
a1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]])

In [13]:
#mathamatical operation in numpy|

In [14]:
lst=[1,2,3,4,5,6]
lst.append(10)

In [15]:
lst

[1, 2, 3, 4, 5, 6, 10]

In [16]:
lst

[1, 2, 3, 4, 5, 6, 10]

In [17]:
lst.remove(6)

In [18]:
lst

[1, 2, 3, 4, 5, 10]

In [19]:
for i in lst:
    i=i+10
    print(i)

11
12
13
14
15
20


In [20]:
lst

[1, 2, 3, 4, 5, 10]

In [21]:
for i in range(len(lst)-1):
    lst[i]+=10
lst    

[11, 12, 13, 14, 15, 10]

In [22]:
lst

[11, 12, 13, 14, 15, 10]

In [23]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [24]:
a+10

array([11, 12, 13, 14, 15])

In [25]:
a

array([1, 2, 3, 4, 5])

In [26]:
a-10

array([-9, -8, -7, -6, -5])

In [27]:
a

array([1, 2, 3, 4, 5])

In [28]:
a*2

array([ 2,  4,  6,  8, 10])

In [29]:
a

array([1, 2, 3, 4, 5])

In [30]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [31]:
a

array([1, 2, 3, 4, 5])

In [32]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [33]:
#trignometric functions

In [34]:
angles=np.array([30,45,55,22])

In [35]:
np.sin(angles)

array([-0.98803162,  0.85090352, -0.99975517, -0.00885131])

In [36]:
np.tan(angles)

array([-6.40533120e+00,  1.61977519e+00, -4.51830879e+01,  8.85165604e-03])

In [37]:
#linear algebra

In [38]:
a=np.full((3,3),2)

In [39]:
a

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [40]:
b=np.full((3,3),3)

In [41]:
b

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [8]:
import numpy as np
c=np.matmul(a,b)

NameError: name 'a' is not defined

In [9]:
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
c=np.identity(4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.linalg.det(c)

1.0

In [12]:
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])